name = "yume"
author = "-"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0abfe614bc0a556b9d2c56dd2ddaff517d9bd69688925d5bd13979a0006e8c66"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
