name = "yume"
author = "-"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d55fcffb13075cd1b4190d9741132ea14b934fd37936f530c5193e8ef9f56429"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
