name = "yume"
author = "-"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8da62d168f2dde7e316e9a1985b6673b6aaee056ae08f937901bb49ff98a3f5"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
